IMAGE_NAME = "ubuntu/focal64"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.memory = 4096
    v.cpus = 4
  end

  # Defining minikube vm
  config.vm.define "minikube", primary: true do |kube|
    kube.vm.box = IMAGE_NAME
    kube.vm.hostname = "minikube"

    kube.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/minikube-playbook.yml"
    end
  end
end
