name: continuous-integration

on:
  push:
    tags-ignore:
      - "v*"
  pull_request:

env:
  GO_VERSION: ^1.17

jobs:
  ##############################################################################
  # BUILD
  ##############################################################################
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # installing latest go version
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      # defining our cache path
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # install dependencies if no cache or if cache is stale
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download
      # build it
      - name: Building
        run: go build -v ./go/...
  ##############################################################################
  # TEST
  ##############################################################################
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # installing latest go version
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      # defining our cache path
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # install dependencies if no cache or if cache is stale
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download
      # test it
      - name: Unit Testing
        run: go test -v ./go/...
